@startuml test

hide circle
hide empty members
hide empty methods

skinparam classAttributeIconSize 0

skinparam roundcorner 5

skinparam class {
	BackgroundColor AliceBlue
	BorderColor DarkSlateGray
	ArrowColor Black
	FontColor Black
	FontSize 12
	FontName Helvetica
}

skinparam arrow {
    MessageAlign center
}

class Chantier{
    +dateD 
    +dateF
    +adresse
} 

class Artisan{
    +salaire 
    +horaire
    +coordonnées
}

class Paye{
    +salaire
}

Chantier "0..*" - "0..*" Artisan
(Chantier, Artisan) .. Paye

@enduml
